# Generated by Django 3.0.6 on 2020-05-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('transportProviders', '0001_initial'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transportProvider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportProviders.TransportProvider'),
        ),
    ]
