# Generated by Django 3.0.6 on 2020-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200517_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hour',
            field=models.CharField(max_length=30),
        ),
    ]
