# Generated by Django 3.0.6 on 2020-05-13 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportProviders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('transportProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportProviders.TransportProvider')),
            ],
        ),
    ]
