# Generated by Django 3.0.6 on 2020-05-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_trasnport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='trasnport',
            new_name='transport',
        ),
    ]
